system: 
  port: 3000
  api_version: 1
  characters: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
  expiryOtp: 60
  numberCharactersOtp: 4
  mail: 
    sendDefault: 
      mail: app.haris.service@gmail.com
      pass: mqaishuixqiyjrln
database: 
  harisPrd:
    host: ep-winter-queen-157000.us-east-2.aws.neon.tech
    username: hungpham1912
    password: vgeiSZ8kdxI3
    database: haris-messenger-prod
    port: 5432
jwt:
  secret: zzzzz
source: 
  user:
    defaultAvatar: https://www.google.com/url?sa=i&url=https%3A%2F%2Fthoitrangwiki.com%2Fbo-suu-tap-99-anh-dai-dien-facebook-trang-chat-luong-full-hd-vi-cb.html&psig=AOvVaw1Dvh3Xe0aLMtDIAkP11D6Z&ust=1678603728237000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCPj77Kik0_0CFQAAAAAdAAAAABAI
  conversation: 
    defaultAvatar: https://static.vecteezy.com/system/resources/previews/009/645/737/non_2x/team-icon-logo-illustration-user-group-network-symbol-template-for-graphic-and-web-design-collection-free-vector.jpg
  merchant: 
    lengthMerchantCode: 32
vietQR: 
  clientID: 4cdbdd44-f150-411f-930b-2339cb741f82
  apiKey: 09a3358c-79df-4da8-9645-bf32e3cf8eec
  baseUrl: https://api.vietqr.io
momo:
  # baseUrl: https://payment.momo.vn
  baseUrl:  https://test-payment.momo.vn
  callBackUrl:  
dropbox:
  baseUrlContent:  https://content.dropboxapi.com
  baseUrlApi: https://api.dropboxapi.com
  # accessToken: sl.Bb4ZdWxtswZPjPKYriTBrwsIr5ldFtZMPc7EZTUBU8iQFGFIXcrCs4eg6SrayPxp3TgEL8nCbeQt-RM2FemG-BlICBT9JPWBaojo9L610axUJJvbFof66tCj26Ga3NKOKNlygNsZ--Iz
  accessToken: sl.Bb7IXdEjspduAfnSj8mbGWJPJnztIgpo0Ver7VKHkpPp15hJLHoyPk1KzkBwTUaNTkKzjyoFcphRFIMYE9mCojRHWLmTEb4Rdus_TtQYziz9-OR8aNPzleybtzRmHhuwAwqMJa9JzIkD
  path: /file-key/
facebook:
  accessToken: EAAGNO4a7r2wBABMFrWEANcMEhCnBaEq95MHKyqwMigFUMdja2zJSFY7jBtUfcLH2GZBVZA7qja4RGWjnr3zC1MURhTnBzQjWXXtwrGtYueZBuI171blzprzIsRxF8dVNklapZC1jGI9gVFcraV4ysRyvCYg0C4G4CeLZCXVcDDfPJAYycsZCoz
  baseUrl: https://graph.facebook.com/v16.0/
storage: 
  baseUrl: https://haris-storage.000webhostapp.com/